# Generated by Django 3.2.6 on 2021-08-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_obj', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=100)),
                ('number_of_pages', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('publisher', models.CharField(max_length=100)),
                ('authors', models.TextField(default='[]')),
            ],
        ),
    ]
